#!/bin/sh

if [ -e /usr/share/tuxdroid/py4tux/bin/python ]; then
  /usr/share/tuxdroid/py4tux/bin/python main.py "${1}"
else
  echo "\033[31mPython 2.6 (py4tux) not found. Run 'sudo bin/install'.\033[0m"
fi